project:
  type: website

website:
  title: ""
  navbar:
    title: false
    pinned: true
    left:
      - text: "Nina Dombrowski"
        file: index.qmd
    right:
      - blog.qmd
      - projects.qmd
      - cv.qmd
      - publications.qmd
      - resources.qmd
      - contact.qmd
      - icon: github
        href: https://github.com/ndombrowski
      - icon: twitter
        href: https://twitter.com/n_dombrowski
      - icon: linkedin
        href: https://www.linkedin.com/in/nina-dombrowski-nd01/
format:
  html:
    theme: theme.scss

execute:
  eval: false
  freeze: auto  # re-render only when source changes
