---
title: "{{< fa chalkboard-user >}} Resources"
toc: true
toc-depth: 2
---


## Teaching

Here the links to the courses I have given in the past:

- [Microbial Ecology: Sequence Data Analysis](https://ndombrowski.github.io/MicEco2025/)
- [Big Biological Data: De novo transcriptomics](https://github.com/ndombrowski/BBDA_2025_material/tree/main)

Here are some general programming tutorials I have created that you might find useful:

- [A tutorial on using UNIX and an HPC](https://ndombrowski.github.io/cli_workshop/)
- [Getting started with the command line](https://ndombrowski.github.io/Unix_tutorial/#sed-manipulating-files) including [example files](https://github.com/ndombrowski/Unix_tutorial)
- [An introduction to AWK](https://ndombrowski.github.io/AWK_tutorial/) with [example files](https://github.com/ndombrowski/AWK_tutorial)
- [An R cookbook](https://ndombrowski.github.io/R_cookbook) with [example files](https://github.com/ndombrowski/R_cookbook)
- [Data manipulation with dplyr](https://ndombrowski.github.io/Tidyverse_tutorial/)
- [Data visualization with ggplot2](https://github.com/ndombrowski/Ggplot_tutorial)

For biologists, I also have tutorials on:

- [Assembling a metagenome](https://ndombrowski.github.io/Assembly_tutorial/)
- [Genomic binning](https://ndombrowski.github.io/Binning_tutorial//index.html)
- [Annotating microbial genomes](https://github.com/ndombrowski/Annotation_workflow)
- [How to do phylogenetic analyses](https://ndombrowski.github.io/Phylogeny_tutorial/) with [example files](https://github.com/ndombrowski/Phylogeny_tutorial)


## Videos

Here, you will find a lecture I gave as part of a workshop where I taught students about metagenomic assemblies, binning and annotations:

{{< video https://youtu.be/2wwAmdqtSSc >}}


A talk I gave at the UBC in April 2021 where I discuss how Undinarchaeota illuminate DPANN phylogeny and the impact of gene transfer on evolution:

{{< video https://www.youtube.com/watch?v=6whnZfdFZTw&t=16s >}}

